language: cpp

compiler:
    - clang
    - gcc

script:
    - if [ "$CXX" == "clang++" ]; then make linux-clang; fi
    - if [ "$CXX" == "g++" ]; then make linux-gcc; fi

notifications:
    email: false

branches:
    only:
        - master
